### ISSUE TITLE
Remove schemaLocation attribute from all test cases

### ISSUE THREAD

**Issue by gtback** [STIXProject/schemas-test#2]
We should not have a schemaLocation in any test case, as documents in this repository should be tested against a version of the schemas in the STIXProject/schemas repo. 

@bschmoker: can you look at this?

**Comment by taraxvoid** [comment]
Keep in mind that schemaloc shouldn't (with caveat) affect anything since we're not passing `--use-schema-loc` to the test script

**Comment by gtback** [comment]
Yep! And I plan to remove that argument entirely from the test script.

EDIT: I removed the `--schema-dir` argument in STIXProject/schemas@200b48347c3e7dc63aa76e41ebce84b519eb492f

**Comment by taraxvoid** [comment]
@gtback Wait, :rewind: - The --schema-dir arg is important since it dictates that the script should use the local version of the schema (1.2), rather than the built-in one (1.1.1)

Without that, it wouldn't actually be checking the right thing

**Comment by nemonik** [comment]
With java-stix validation I have authored have taken to stripping the
schemaLocation off prior to validation, because the relative paths
(../whatever/whatever.xsd) of the python example docs cause the java
validator to shoot itself in the head and splatter brain matter all over
the place... Best practice is never trust a remote schema any how.

-Michael

**Comment by gtback** [comment]
@bschmoker: The `--schema-dir` argument to `runner.py` was removed, since we always want to use the current directory of schemas. I do explicitly pass this directory into the `STIXSchemaValidator` class constructor, see https://github.com/STIXProject/schemas/blob/200b48347c3e7dc63aa76e41ebce84b519eb492f/test_runner.py#L103-L106

@nemonik: Yes, relying on `schemaLocation` is a crutch, and in this case we are not actually relying on the `schemaLocation` attribute when determining the version of schemas to use for validation. My point in removing it was to avoid confusion by people who see the attribute and think it is actually being used, and needs to be updated with new versions of the schema, etc.

**Comment by taraxvoid** [comment]
@gtback Ah I see, if it works then :+1: though IMO it makes the script a bit more 'magical' and less explicit.

**Comment by gtback** [comment]
I suppose I could have left the argument but just give it a default value. My ultimate goal is to make the command easy to run from your host (not just via Travis) to support frequent testing _before_ pushing commits (by removing as many options and flags as possible).

**Comment by nemonik** [comment]
Yeah, and on top of that with JAXP fails if one leaves the "schemaLocation"
attribute on the document being validated in a manner that isn't
immediately obvious.  The funny thing is both Jason I were discussing this
concern the same day I go home and see this thread.  Like minds at a
distance.  Spooky!
